# Update this file:
#   pre-commit autoupdate

default_language_version:
  python: python3.11
files: "^lambda_functions/spotify_daily"
repos:

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        entry: flake8
        args: ["--config=lambda_functions/spotify_daily/.flake8"]


  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
        args: [--line-length, '120', --include, '\.py$', --exclude, '/(\.git|\.hg|\.mypy_cache|\.tox|\.venv|_build|buck-out|build|dist|flake8-isort_build)/']

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort
        args: ["--profile", "black"]
