version: 2.1

orbs:
  python: circleci/python@3.11.3

jobs:
  run_python_test:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: python -m pytest
      - persist_to_workspace:
          root: ~/lambda_functions/spotify_daily
          paths:
            - .

  deploy_infra:
    executor: python/default
    steps:
      - attach_workspace:
          at: ~/project
      - heroku/deploy-via-git:
          force: true # force push when pushing to the heroku remote, see: https://devcenter.heroku.com/articles/git

workflows:
  test_my_app:
    jobs:
      - run_python_test
      - deploy:
          requires:
            - run_python_test
          filters:
            branches:
              only: main
