version: 2.1

orbs:
  python: circleci/python@2.1.1
  node: circleci/node@5.2.0
  aws-cli: circleci/aws-cli@2.0.6
  # aws-ecr: circleci/aws-ecr@7.3.0

executors:
  python-executor:
    docker:
      - image: cimg/python:3.11

jobs:
  run_python_test:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Run tests
          command: |
            cd lambda_functions/spotify_daily
            pip install -r requirements.txt
            python -m pytest

  deploy_infra_basestack:
    docker:
        - image: cimg/python:3.11-node
          user: root
    steps:
      - checkout
      - run:
          name: Install AWS CDK
          command: npm install -g aws-cdk
      - run:
          name: Deploy BaseStack
          command: |
            cd infra
            echo "Install Python requirements"
            pip install -r requirements.txt
            echo "Deployment with CDK"
            cdk synth
            cdk diff
            cdk deploy BaseStack



workflows:
  deploy_my_dataeng_project:
    jobs:
      - run_python_test
      - deploy_infra_basestack:
          requires:
            - run_python_test
          # filters:
          #   branches:
          #     only: main