version: 2.1

orbs:
  python: circleci/python@2.1.1
  aws-cli: circleci/aws-cli@2.0.6
  aws-ecr: circleci/aws-ecr@7.3.0

jobs:
  run_python_test:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: python -m pytest
      - persist_to_workspace:
          root: ~/lambda_functions/spotify_daily
          paths:
            - .

  deploy_infra_basestack:
    executor: python/default
    steps:
      - attach_workspace:
          at: ~/infra
      - run:
          name: Deploy BaseStack
          command: |
            cd infra
            cdk synth
            cdk diff
            cdk deploy BaseStack


workflows:
  test_my_app:
    jobs:
      - run_python_test
      - deploy_infra_basestack:
          requires:
            - run_python_test
          filters:
            branches:
              only: main
