version: 2.1

orbs:
  python: circleci/python@2.1.1
  aws-cli: circleci/aws-cli@2.0.6
  aws-ecr: circleci/aws-ecr@7.3.0

jobs:
  run_python_test:
    executor: python/default
    # working_directory: /lambda_functions/spotify_daily
    steps:
      - checkout
      # - python/install-packages:
      #     pkg-manager: pip
      - run:
          name: Run tests
          command: |
            cd lambda_functions/spotify_daily
            pip install -r requirements.txt
            python -m pytest

  deploy_infra_basestack:
    executor: python/default
    steps:
      - attach_workspace:
          at: ~/infra
      - run:
          name: Deploy BaseStack
          command: |
            cd infra
            pip install -r requirements.txt
            cdk synth
            cdk diff
            cdk deploy BaseStack


workflows:
  deploy_my_dataeng_project:
    jobs:
      - run_python_test
      - deploy_infra_basestack:
          requires:
            - run_python_test
          filters:
            branches:
              only: main
