name: GitHub Actions checks

run-name: ${{ github.actor }} is checking linting and formating in order to merge Pull Request

on:
  pull_request:
    branches:
      - main

defaults:
  run:
    working-directory: .

jobs:
  Check-Ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff
      - name: Run Ruff Linting
        run: ruff check --output-format=github .
      - name: Run Ruff Formating
        run: ruff format --check --line-length=120
      - run: echo "🍏 This Formating and Linting job's status is ${{ job.status }}."